/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * SolarEnrollment.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateEnrollmentRequest {
  firstName?: string;
  lastName?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  utility?: string;
  utilityAccountNumber?: string;
  hasAssistanceProgram?: boolean;
  /** @nullable */
  assistancePrograms?: string[] | null;
}
