/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * SolarEnrollment.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ValidateAddressResponse {
  isValid?: boolean;
  /** @nullable */
  normalizedAddress?: string | null;
  /** @nullable */
  errorMessage?: string | null;
}
