/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * SolarEnrollment.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ValidateAddressRequest {
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
}
