/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * SolarEnrollment.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreateEnrollmentRequest,
  CreateEnrollmentResponse,
  ValidateAddressRequest,
  ValidateAddressResponse,
} from ".././model";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const validateAddress = (
  validateAddressRequest: ValidateAddressRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ValidateAddressResponse>(
    {
      url: `/api/address/validate`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: validateAddressRequest,
      signal,
    },
    options,
  );
};

export const getValidateAddressMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateAddress>>,
    TError,
    { data: ValidateAddressRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateAddress>>,
  TError,
  { data: ValidateAddressRequest },
  TContext
> => {
  const mutationKey = ["validateAddress"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateAddress>>,
    { data: ValidateAddressRequest }
  > = (props) => {
    const { data } = props ?? {};

    return validateAddress(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateAddressMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateAddress>>
>;
export type ValidateAddressMutationBody = ValidateAddressRequest;
export type ValidateAddressMutationError = unknown;

export const useValidateAddress = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateAddress>>,
      TError,
      { data: ValidateAddressRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validateAddress>>,
  TError,
  { data: ValidateAddressRequest },
  TContext
> => {
  const mutationOptions = getValidateAddressMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const createEnrollment = (
  createEnrollmentRequest: CreateEnrollmentRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateEnrollmentResponse>(
    {
      url: `/api/enrollment`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createEnrollmentRequest,
      signal,
    },
    options,
  );
};

export const getCreateEnrollmentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEnrollment>>,
    TError,
    { data: CreateEnrollmentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: CreateEnrollmentRequest },
  TContext
> => {
  const mutationKey = ["createEnrollment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEnrollment>>,
    { data: CreateEnrollmentRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createEnrollment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEnrollment>>
>;
export type CreateEnrollmentMutationBody = CreateEnrollmentRequest;
export type CreateEnrollmentMutationError = unknown;

export const useCreateEnrollment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createEnrollment>>,
      TError,
      { data: CreateEnrollmentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: CreateEnrollmentRequest },
  TContext
> => {
  const mutationOptions = getCreateEnrollmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
