/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * SolarEnrollment.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CreateEnrollmentRequest,
  CreateEnrollmentResponse,
  ValidateAddressRequest,
  ValidateAddressResponse,
} from ".././model";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint =
  (
    validateAddressRequest: ValidateAddressRequest,
    options?: SecondParameter<typeof customInstance>,
    signal?: AbortSignal,
  ) => {
    return customInstance<ValidateAddressResponse>(
      {
        url: `/api/address/validate`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: validateAddressRequest,
        signal,
      },
      options,
    );
  };

export const getSolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpointMutationOptions =
  <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
        >
      >,
      TError,
      { data: ValidateAddressRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
      >
    >,
    TError,
    { data: ValidateAddressRequest },
    TContext
  > => {
    const mutationKey = [
      "solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint",
    ];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
        >
      >,
      { data: ValidateAddressRequest }
    > = (props) => {
      const { data } = props ?? {};

      return solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint(
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type SolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpointMutationResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
      >
    >
  >;
export type SolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpointMutationBody =
  ValidateAddressRequest;
export type SolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpointMutationError =
  unknown;

export const useSolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint =
  <TError = unknown, TContext = unknown>(
    options?: {
      mutation?: UseMutationOptions<
        Awaited<
          ReturnType<
            typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
          >
        >,
        TError,
        { data: ValidateAddressRequest },
        TContext
      >;
      request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
  ): UseMutationResult<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsValidateAddressValidateAddressEndpoint
      >
    >,
    TError,
    { data: ValidateAddressRequest },
    TContext
  > => {
    const mutationOptions =
      getSolarEnrollmentApiEndpointsValidateAddressValidateAddressEndpointMutationOptions(
        options,
      );

    return useMutation(mutationOptions, queryClient);
  };
export const solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint =
  (
    createEnrollmentRequest: CreateEnrollmentRequest,
    options?: SecondParameter<typeof customInstance>,
    signal?: AbortSignal,
  ) => {
    return customInstance<CreateEnrollmentResponse>(
      {
        url: `/api/enrollment`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createEnrollmentRequest,
        signal,
      },
      options,
    );
  };

export const getSolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpointMutationOptions =
  <TError = unknown, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
        >
      >,
      TError,
      { data: CreateEnrollmentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
      >
    >,
    TError,
    { data: CreateEnrollmentRequest },
    TContext
  > => {
    const mutationKey = [
      "solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint",
    ];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
        >
      >,
      { data: CreateEnrollmentRequest }
    > = (props) => {
      const { data } = props ?? {};

      return solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint(
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type SolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpointMutationResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
      >
    >
  >;
export type SolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpointMutationBody =
  CreateEnrollmentRequest;
export type SolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpointMutationError =
  unknown;

export const useSolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint =
  <TError = unknown, TContext = unknown>(
    options?: {
      mutation?: UseMutationOptions<
        Awaited<
          ReturnType<
            typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
          >
        >,
        TError,
        { data: CreateEnrollmentRequest },
        TContext
      >;
      request?: SecondParameter<typeof customInstance>;
    },
    queryClient?: QueryClient,
  ): UseMutationResult<
    Awaited<
      ReturnType<
        typeof solarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpoint
      >
    >,
    TError,
    { data: CreateEnrollmentRequest },
    TContext
  > => {
    const mutationOptions =
      getSolarEnrollmentApiEndpointsCreateEnrollmentCreateEnrollmentEndpointMutationOptions(
        options,
      );

    return useMutation(mutationOptions, queryClient);
  };
